### ISSUE TITLE
License

### ISSUE THREAD

**Issue by 0xbe7a** [cholcombe973/libatasmart#3]
Could you please add a license to this packag so people know how they are allowed to use the code?

**Comment by cholcombe973** [comment]
Yeah no problem.  It's MIT.  Let me do that now

**Comment by cholcombe973** [comment]
https://github.com/cholcombe973/libatasmart/pull/4

**Comment by cholcombe973** [comment]
I'm available on #rust on mozilla irc if you need any help with this library.  Or feel free to open an issue here :)
